services:
  db:
    container_name: postgres_container
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
      
  app:
    build:
      context: ./app
    container_name: django-app
    restart: always
    env_file:
      - .env
    volumes:
      - static:/static 
      - ./media:/DSA_Website_v1/local_contest/media
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    ports:
      - "80:80"
    volumes:
      - static:/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network


networks:
  app-network:

volumes:
  static:
