# Generated by Django 5.0.4 on 2024-05-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="input_file",
            field=models.FileField(
                blank=True, null=True, upload_to="level_input_files/"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="description",
            field=models.FileField(
                blank=True, null=True, upload_to="level_descriptions/"
            ),
        ),
    ]
