# Generated by Django 5.0.4 on 2024-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_level_input_file_alter_level_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="description_file",
            field=models.FileField(
                blank=True, null=True, upload_to="level_descriptions/"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
