# Generated by Django 5.0.4 on 2024-05-04 12:35

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0004_alter_level_description_file_alter_level_input_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="definedfile",
            name="input_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=challenges.models.DefinedFile.upload_to_input_file,
            ),
        ),
    ]
