# Generated by Django 5.0.4 on 2024-05-04 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0005_definedfile_input_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="definedfile",
            name="content",
        ),
    ]
