# Generated by Django 5.0.4 on 2024-05-04 15:42

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0006_remove_definedfile_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="definedfile",
            name="output_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=challenges.models.DefinedFile.upload_to_output_file,
            ),
        ),
    ]
