# Generated by Django 5.0.4 on 2024-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0010_performance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
