# Generated by Django 5.0.4 on 2024-05-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0012_alter_performance_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="author",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
