# Generated by Django 5.0.4 on 2024-12-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_userattendance_time_alter_userattendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userattendance",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
