# Generated by Django 5.0.4 on 2024-05-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="graduation_field",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
