# Generated by Django 5.0.4 on 2024-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_customuser_graduation_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="category",
            field=models.CharField(
                choices=[
                    ("Alpha", "Alpha"),
                    ("Beta", "Beta"),
                    ("Gamma", "Gamma"),
                    ("Omega", "Omega"),
                ],
                default="Alpha",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="graduation_field",
            field=models.CharField(default="L1_v1", max_length=50),
        ),
    ]
