# Generated by Django 5.0.4 on 2024-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_customuser_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="graduation_field",
            field=models.CharField(
                choices=[
                    ("L1_v1", "L1_v1"),
                    ("L1_v2", "L1_v2"),
                    ("L2_IAD", "L2_IAD"),
                    ("L2_GL", "L2_GL"),
                    ("L2_ARSB", "L2_ARSB"),
                ],
                default="L1_v1",
                max_length=10,
            ),
        ),
    ]
