# Generated by Django 5.0.4 on 2024-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_alter_customuser_graduation_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
