# Generated by Django 5.0.4 on 2024-05-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_customuser_rank_customuser_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
